name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build backend
        run: docker build -t cicd-backend ./backend

      - name: Build frontend
        run: docker build -t cicd-frontend ./frontend
